<?php

/**
 * @file
 * Provides a rsvp confirm entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function rsvp_confirm_theme() {
  return [
    'rsvp_confirm' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for rsvp confirm templates.
 *
 * Default template: rsvp-confirm.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the rsvp confirm information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_rsvp_confirm(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
